### ISSUE TITLE
Plug in doesn't seem to work

### ISSUE THREAD

**Issue by stoweboyd** [macrojd/tag-summary#2]
I installed via BRAT, enabled, but doesn't seem to do anything.

\```add-summary
tags: #work/996 

\```

**Comment by macrojd** [comment]
Hi. I never used BRAT. This is my first plugin so I don't even know what that is :-). But I inserted your same tag on a paragraph and then created the summary with that tag and it worked perfectly. I'm not sure what could be the problem. Try using the command to insert the block (Add Summary).

**Comment by stoweboyd** [comment]
How then am I supposed to install it? It's not on the list of community plugins.

**Comment by macrojd** [comment]
Hi. I'm not sure if there is a good way to install a plugin that hasn't been approved by the community yet. To test my plugin, I just copy the files inside a folder, as explained in this post https://forum.obsidian.md/t/plugins-mini-faq/7737

I just developed this plugin last week and followed the instructions to include it in the Obsidian's list of plugins. The first step is to upload the plugin to GitHub, then report it, and then wait. Nobody else is supposed to find or use this plugin at the moment. That's why I don't provide any instructions to install it. The only reason you find it here is because I'm waiting for Obsidian's developers to approve it. That can take several days. It's outside my control.

**Comment by stoweboyd** [comment]
I'll wait until the plugin is released.

Thanks

| Stowe

**Comment by oldtowneast** [comment]
> I'll wait until the plugin is released. Thanks | Stowe

I have the same problem you do but it's another plugin causing the conflict. I popped a new vault and installed only this plugin and it worked just fine. I have 116 plugins installed I have not figured out what one it is yet but I'll report back here when I do!

I started a thread on reddit here: https://www.reddit.com/r/ObsidianMD/comments/v5t8xa/anyone_else_having_issues_with_the_new_tag/

**Comment by stoweboyd** [comment]
Aha!

**Comment by macrojd** [comment]
> I have the same problem you do but it's another plugin causing the conflict. I popped a new vault and installed only this plugin and it worked just fine. I have 116 plugins installed I have not figured out what one it is yet but I'll report back here when I do!
> 
> I started a thread on reddit here: https://www.reddit.com/r/ObsidianMD/comments/v5t8xa/anyone_else_having_issues_with_the_new_tag/

Thanks for the info. That makes sense. I would probably start by checking plugins that work with code blocks as well (the blocks created with the ``` characters), and then maybe check those that modify the markup somehow. 

Because I'm getting messages everywhere, I've decided to create a post on Obsidian's forum. Please share any tips or suggestions there, so I don't miss anything.

https://forum.obsidian.md/t/tag-summary-plugin/38648

Thanks
JD

**Comment by oldtowneast** [comment]
I'm responding here because that guy on the forums seems to want to be a dick about you making a plugin.  His suggestion is also **hot garbage ** compared to this plugin. 

Firstly, I must apologize I haven't been involved in any sort of tech stuff in over twenty years so I probably sound like English isn't my primary language. :\

I simply cannot for the life of me figure out what plugin it is that making this conflict.  Every plugin that changed or manipulated code blocks was not it.  When I popped that new vault I swore that had to be the issue.  However, I made a duplicate of my vault and and opened that up and **disabled** all plugins except for tag-summary and again it didn't work.

That got me to thinking it may have been a theme issue but that is not the case either.  I've been banging my head against the wall with this all day, I really wish I could be of more use.  

This is my output in the console when I switch to preview mode: https://gist.github.com/oldtowneast/22382a6dea77aa6bc8b70db5e2894119

**Comment by macrojd** [comment]
Hi. I wonder if you can try the old version of the plugin instead (0.2.1).
https://github.com/macrojd/tag-summary/releases

Your logs mention that the issue is in "promise", which is the code that reads the files. In the older version, I used a different code to read the files, so maybe we can find the issue there.

Just remember that In the old version only the tags: label is available (you cannot use include: or exclude:).

JD

**Comment by oldtowneast** [comment]
> Hi. I wonder if you can try the old version of the plugin instead (0.2.1).

Just got out of the shop now. I will look into this right now!

**Comment by oldtowneast** [comment]
Unfortunately that rendered the "There are no blocks with the specified tags." output.  
This may be worth mentioning because prior to this it was only rendering a blank page.

**Comment by macrojd** [comment]
Just in case, I ask. Did you use the command to insert the code block? If not, try using the command (Add Summary) and select a tag that you are sure exists (preferably one that is present in different files). This is to make sure that the error is not because of any typos.

**Comment by oldtowneast** [comment]
I did. Typos did not seem to be the error here. Let me know if there is any hacking and cracking I can do on your behalf!

**Comment by macrojd** [comment]
Thanks, man. I'm very busy this week. I'll see if I can review the code in the next few days and submit a new version. I'll post a message here to let you know.

**Comment by macrojd** [comment]
Hi, oldtowneast. I released a new version (1.0.2). I improved the code that reads the files. I was using a piece of code suggested by someone at Obsidian's forum but it was not reliable. I replaced it with my own code so now I know it works well.

https://github.com/macrojd/tag-summary/releases/tag/1.0.2

I've tested this version with other plugins and everything works. If it still doesn't work for you, maybe you can send me a list of the plugins you are using for me test. That'd be great.

Thanks for the help
JD

**Comment by stoweboyd** [comment]
Still doesn't work. Reinstalled, restarted.

community plugins

txt as md
todoist plugin
tag wrangler
style settings
sortable
sliding panes
simple embeds
reminder
recent files
readwise official
pluck
periodic notes
obsius publish
obsidian42 - BRAT
multi-line formatting
minimal theme settings
local rest api
kanban
hover editor
footnote shortcut
extract highlights
excalidraw
drag-n-drop for blocks
dataview
custom frames
copy block link
calendar
better word count
better footnote
auto note mover
archiver

**Comment by macrojd** [comment]
OK, guys. I think it is working now. It seems that it wasn't another plugin causing the issue but just my own stupidity. It happens... :-)

The new version is 1.1.0

Let me know if you find any issues.
JD

**Comment by oldtowneast** [comment]
> It happens...

Damn right it happens! I will give it a go around right now thank you!

**Comment by oldtowneast** [comment]
All is well! :tada:

**Comment by macrojd** [comment]
Awesome! I'll see if I can get it into the community plugins. Thanks for all the help. I couldn't have done it without you.

**Comment by stoweboyd** [comment]
Yes, it does seem to work. 

An additional toggle to collate all hits from a single file with just one file reference would be good. 

Alternatively, a toggle that pulls all highlights from a file in which the tag appears once or more (more complicated, I know).
